stage("Docker Image Build"){
    steps{
        dir('Code') {
            script{
                withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                    withCredentials([string(credentialsId: 'mock-api', variable: 'MOCK_API_URL')]) {
                        sh """
                            docker build \
                                --build-arg VITE_API_URL="${VITE_API_URL}" \
                                -t restaurant-app:latest .
                        """
                    }
                }
            }
        }
    }
}
